# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GadakCli < Formula
  desc "Local SQLite mirror of your Jira issues — web UI and agent SQL"
  homepage "https://github.com/midagedev/gadak"
  version "0.23.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/gadak/releases/download/v0.23.0/gadak_0.23.0_darwin_amd64.tar.gz"
      sha256 "d4349a604f242fa207607a22fe28710b35859eaf508b78a9afde0362e25feb73"

      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/gadak/releases/download/v0.23.0/gadak_0.23.0_darwin_arm64.tar.gz"
      sha256 "2212612a50f7cac61a36698aa5422da55dea10c9686e3c013a7422a64963cd75"

      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.23.0/gadak_0.23.0_linux_amd64.tar.gz"
      sha256 "b6267cac2dfb545e39d47c610f7a31b565bdf29b665e41466b1cf4c6b52ad134"
      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.23.0/gadak_0.23.0_linux_arm64.tar.gz"
      sha256 "0ecd088f4e7f49fa6411fd5129b1a475f8910b19d58edf51d79d60dfebdcdc20"
      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  test do
    system "#{bin}/gadak", "version"
  end
end
