# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GadakCli < Formula
  desc "Local SQLite mirror of your Jira issues — web UI and agent SQL"
  homepage "https://github.com/midagedev/gadak"
  version "0.15.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/gadak/releases/download/v0.15.1/gadak_0.15.1_darwin_amd64.tar.gz"
      sha256 "470c5d051a50e0eb2145af2cc8a047803177ec1b85a8ff39ff22d159eb872319"

      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/gadak/releases/download/v0.15.1/gadak_0.15.1_darwin_arm64.tar.gz"
      sha256 "2cd29e60518d1ea688f9a56161cf7af1627dc49735fe49e4fd762b5d471b1ad0"

      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.15.1/gadak_0.15.1_linux_amd64.tar.gz"
      sha256 "a36ad592fb29950dc57690068c5738eb31a0ad6d4bf60fffa0fbaa0e04323bab"
      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.15.1/gadak_0.15.1_linux_arm64.tar.gz"
      sha256 "27f09ebde1ec820be18bead8bd72e1fc4d925845e522777538b8f506dba6a142"
      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  test do
    system "#{bin}/gadak", "version"
  end
end
