# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GadakCli < Formula
  desc "Local SQLite mirror of your Jira issues — web UI and agent SQL"
  homepage "https://github.com/midagedev/gadak"
  version "0.24.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/gadak/releases/download/v0.24.0/gadak_0.24.0_darwin_amd64.tar.gz"
      sha256 "c641a077c79ee314c3e262813d20f8aab0d817d3a1eb1dd6e121aa3f4b27bd54"

      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/gadak/releases/download/v0.24.0/gadak_0.24.0_darwin_arm64.tar.gz"
      sha256 "673629d07dadaead9c1ccc079b23971813041e790a08265490dad5d951b96f2e"

      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.24.0/gadak_0.24.0_linux_amd64.tar.gz"
      sha256 "e826dd536001e00d11d8697de00e399f9de72d7f12afb381d176d0b97a220b68"
      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.24.0/gadak_0.24.0_linux_arm64.tar.gz"
      sha256 "cb04a15216f42ed84e7127750239a7c863cbbb67f236a3dc52dcc8098e9e6f05"
      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  test do
    system "#{bin}/gadak", "version"
  end
end
