# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gadak < Formula
  desc "Local SQLite mirror of your Jira issues — web UI and agent SQL"
  homepage "https://github.com/midagedev/gadak"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/gadak/releases/download/v0.12.0/gadak_0.12.0_darwin_amd64.tar.gz"
      sha256 "9432fe7ec081bed70e5600dc0b6affe216eb1b3800af3ffe47ebe843195551d7"

      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/gadak/releases/download/v0.12.0/gadak_0.12.0_darwin_arm64.tar.gz"
      sha256 "b7fba4e0565257db068c77fd0a3aa71d9abaae201596897d14bf828fca570775"

      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.12.0/gadak_0.12.0_linux_amd64.tar.gz"
      sha256 "57e4e3a545405a587fbf144c02ccf2945e8f0825a4a35f05aefaa0f3faa18a44"
      define_method(:install) do
        bin.install "gadak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/gadak/releases/download/v0.12.0/gadak_0.12.0_linux_arm64.tar.gz"
      sha256 "32b361941d9e409029c2a4485b2dea81c86486f29614a67d115ed7099d3d20d0"
      define_method(:install) do
        bin.install "gadak"
      end
    end
  end

  test do
    system "#{bin}/gadak", "version"
  end
end
