# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scry < Formula
  desc "Local SQLite mirror of your Jira issues — web UI, TUI, and agent SQL"
  homepage "https://github.com/midagedev/scry"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/scry/releases/download/v0.8.0/scry_0.8.0_darwin_amd64.tar.gz"
      sha256 "3c44fa5443a632077d79a267b67a1f4d37b4f2b9f4163260553ccac20581a111"

      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/scry/releases/download/v0.8.0/scry_0.8.0_darwin_arm64.tar.gz"
      sha256 "91ffad2ad20eff14eedb34ee6810cbfe259015ebdc309a06b051f7a241e83dd9"

      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/scry/releases/download/v0.8.0/scry_0.8.0_linux_amd64.tar.gz"
      sha256 "d4c66e216ebfba27d8072e0cd56b1736713bceb648e69bd1d6ebb55f5e2c05a9"
      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/scry/releases/download/v0.8.0/scry_0.8.0_linux_arm64.tar.gz"
      sha256 "62eef5a881e35ebcb34a874e260994b592ec5f850b446e9735d892673afbedd4"
      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  test do
    system "#{bin}/scry", "version"
  end
end
