# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scry < Formula
  desc "Local SQLite mirror of your Jira issues — web UI, TUI, and agent SQL"
  homepage "https://github.com/midagedev/scry"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/scry/releases/download/v0.5.0/scry_0.5.0_darwin_amd64.tar.gz"
      sha256 "b66271bad4b37715eb51783a1eb19a6d4c2e758809b33d6b92e4f23cd100c16a"

      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/scry/releases/download/v0.5.0/scry_0.5.0_darwin_arm64.tar.gz"
      sha256 "344aea3440c5d7f2d1244353b7839dd1158f242d80222ae5c0908873b4ff5b70"

      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/scry/releases/download/v0.5.0/scry_0.5.0_linux_amd64.tar.gz"
      sha256 "6471ec39168d91a5a5df2f0737168846fd6951d253b2fa0fbf7cc65a423de8ec"
      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/scry/releases/download/v0.5.0/scry_0.5.0_linux_arm64.tar.gz"
      sha256 "8d39d09c9ddc917662058f088df4c8ee68fb8617f7e3d9f7917bde86e5fb735f"
      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  test do
    system "#{bin}/scry", "version"
  end
end
