# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toktape < Formula
  desc "The black-box tape for local LLM serving"
  homepage "https://github.com/midagedev/toktape"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/toktape/releases/download/v0.2.1/toktape_0.2.1_darwin_amd64.tar.gz"
      sha256 "c684862a3106cddadf3c9a2af2460badec1b01d521636d6ba0632ad1bf81387e"

      define_method(:install) do
        bin.install "toktape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/toktape/releases/download/v0.2.1/toktape_0.2.1_darwin_arm64.tar.gz"
      sha256 "b282cfaa8eabb341950274e5c00c3c71246540a5e30b63d9cdb9c0a3efb95077"

      define_method(:install) do
        bin.install "toktape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/toktape/releases/download/v0.2.1/toktape_0.2.1_linux_amd64.tar.gz"
      sha256 "f7d11c848a407ba10ba2a5c0c87cf56696ec8ba8060a449a3cd71f67d27598e2"
      define_method(:install) do
        bin.install "toktape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/toktape/releases/download/v0.2.1/toktape_0.2.1_linux_arm64.tar.gz"
      sha256 "825caafa41b0e0e9adcaf04cf8cae99372e20982a3b3f91c1f8e1dfd3893eade"
      define_method(:install) do
        bin.install "toktape"
      end
    end
  end

  test do
    system "#{bin}/toktape", "version"
  end
end
