# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toktape < Formula
  desc "The black-box tape for local LLM serving"
  homepage "https://github.com/midagedev/toktape"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/midagedev/toktape/releases/download/v0.5.0/toktape_0.5.0_darwin_amd64.tar.gz"
      sha256 "b0aa272976dfb2b5557fce92e46fea549616a5ebe5ea5399352f3b1c9ea738d1"

      define_method(:install) do
        bin.install "toktape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/midagedev/toktape/releases/download/v0.5.0/toktape_0.5.0_darwin_arm64.tar.gz"
      sha256 "e88769543fb950b42a07779a56301a5f9394d837f5f9be5404194a013bbf9a69"

      define_method(:install) do
        bin.install "toktape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/toktape/releases/download/v0.5.0/toktape_0.5.0_linux_amd64.tar.gz"
      sha256 "9f8f6f446a9cb48eb30f0a6a9ac5c0e9063dd4cde1206bb019050f1f021fc0fe"
      define_method(:install) do
        bin.install "toktape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/midagedev/toktape/releases/download/v0.5.0/toktape_0.5.0_linux_arm64.tar.gz"
      sha256 "81695ad089353df8cc63faf6dcbc5b982057e38bbeb20bcb8f5fd1e748e417ad"
      define_method(:install) do
        bin.install "toktape"
      end
    end
  end

  test do
    system "#{bin}/toktape", "version"
  end
end
